trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
  displayName: 'Restore NuGet Packages'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '**/*.sln'
    vsVersion: 'latest'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebConfigTransform=true'
    platform: 'Any CPU'
    configuration: 'Release'

- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    platform: 'Any CPU'
    configuration: 'Release'